### ISSUE TITLE
Custom build of Bullet 3?

### ISSUE THREAD

**Issue by fabiodr** [lo-th/phy#1]
The lib uses a custom build directly from Bullet 3.1.7 last version?

Could you share the build script and code adaptations needed?

Awesome lib and demo visuals btw!

**Comment by lo-th** [comment]
yes you can find info and build here 
Zentropivity build version 3
https://github.com/kripken/ammo.js/pull/366
code is near same ( but little problem to clear tri mesh of terrain memory )
