### ISSUE TITLE
web demos not loading

### ISSUE THREAD

**Issue by kfarr** [lo-th/phy#12]
https://lo-th.github.io/phy/docs/scenes/engines.html#PHYSX
> ysx.module.js:1     Failed to load resource: the server responded with a status of 404 ()
> Phy.module.js:26368 Uncaught (in promise) TypeError: Failed to fetch dynamically imported module: https://lo-th.github.io/phy/docs/scenes/build/Physx.module.js

**Comment by lo-th** [comment]
is fix thank's
