### ISSUE TITLE
Kinematic object in Physx not effecting a block sitting on top  

### ISSUE THREAD

**Issue by fatbatman** [lo-th/phy#13]
```
let mP
onComplete = () => {
    mP = phy.add({ name:'movingPlatform', type:'box', pos:[0,0,0], size:[10,1,10], restitution:0, friction:0.5, kinematic:true})
    phy.add({type: 'box', material:'chrome', size: [1,1,1], pos: [0, 1.1, 0] })
}

update = () => {
    phy.change( { name:mP.name, pos:[mP.position.x, mP.position.y, mP.position.z+0.1], wake:true } )
}
```

box1 isn't effected by the movement of the platform underneath it when using Physx.

**Comment by lo-th** [comment]
you have to add density to your box 
object without density is static object

**Comment by fatbatman** [comment]
Sorry, I omitted that from the example code.  Both objects have density:1, restitution:0.1, friction:0.5

The box on top falls down when "movingPlatform" moves out from underneath it, but it is not effected by friction before that.  It works as expected with all other engines.

**Comment by lo-th** [comment]
ok is because of substep different from 1
i will see how fixe bug 
you can test platform on 'bridge' demo 

havok is fix
oimo don't have friction ?

**Comment by lo-th** [comment]
for oimo i have to set manually velocity 
so for physx i think he lose velocity on multy substep

**Comment by lo-th** [comment]
ok is fix for all engine look bridge demo 
i have to use différente stratégie 
but now is work with substep or not
