### ISSUE TITLE
cannon-es and  physx-js

### ISSUE THREAD

**Issue by arpu** [lo-th/phy#2]
Hey,
do you have any plans to add this two physics?

**Comment by lo-th** [comment]
Hi 
cannon no i already try but i have perf issue with many body 
physx ;)

**Comment by arpu** [comment]
you know https://github.com/pmndrs/cannon-es ? works fine for me from performance side 
but physx could be awesome

**Comment by lo-th** [comment]
yes cannon is great engine but conversion is difficult 
and basic demo like 'start ' or 'basic' are slow 
maybe i don't use the best option, and is possible i add in future

**Comment by radman-x** [comment]
Almost all these samples run much slower than almost all the cannon-es samples on Android and IOS.

**Comment by lo-th** [comment]
ok is done
