### ISSUE TITLE
add gdb model

### ISSUE THREAD

**Issue by elkizana** [lo-th/phy#24]
Could you add a simple example to how to add a gdb model to the scene ?

**Comment by lo-th** [comment]
sure 
you can look at chess demo

**Comment by elkizana** [comment]
what comes after  :  phy.load("object.glb")  ? 
No need for material

**Comment by elkizana** [comment]
when I try importing a simple box i get this error :
`GLTFLoader.js:219 TypeError: Cannot read properties of undefined (reading 'traverse')
    at Object.onComplete [as callback] (<anonymous>:47:21)
    at Object.next (Pool.js:342:25)
    at Object.add (Pool.js:183:14)
    at Pool.js:540:18
    at GLTFLoader.js:241:6
    at GLTFLoader.js:2630:5
`

**Comment by lo-th** [comment]
you need a callback when loading complete
```
phy.load("yourObject.glb", onComplete)

onComplete = () => {
   let scene = phy.getGlb('yourObject');// is your main scene
   let mat = phy.getGlbMaterial('yourObject');// list of material
   let mesh = phy.getMesh('yourObject' );// for all mesh ex: mesh.model1
   let group = phy.getGroup('yourObject' );// for all group 
}
```

**Comment by elkizana** [comment]
Thank you it is a big thing making all of this  alone
