### ISSUE TITLE
Advice for using phy in Freeciv3D 

### ISSUE THREAD

**Issue by andreasrosdal** [lo-th/phy#25]
Hello! I would like advice about how to use this phy physics engine in Freeciv 3D, which uses Three.js. 
How can I use this physics engine, and what in the game client would benefit from a physics engine? Thank you!

https://github.com/fciv-net/fciv-net
https://www.fciv.net

**Comment by lo-th** [comment]
Hello well is more for a action game :) fps, platformer ...
but you can use in post prod for destruction effect.
