### ISSUE TITLE
Feature  request

### ISSUE THREAD

**Issue by InfoLibre** [lo-th/phy#31]
Hello,

Could you add https://schteppe.github.io/cannon.js/ to the test on https://lo-th.github.io/phy/?

**Comment by lo-th** [comment]
well cannon is in test
but perf with many object is really bad 
i don't find good motor setting to fix that
also is a old motor with few update

**Comment by InfoLibre** [comment]
Indeed, I didn't see it isn't maintained anymore since 8 years. It isn't interesting to add it in your tests.

**Comment by lo-th** [comment]
i always interesting to compare
but performance is bad
