### ISSUE TITLE
(Physx Bug) Calling phy.change({name:xxx, wake:true}) kills the worker if object is not wakable (solid)

### ISSUE THREAD

**Issue by nebular** [lo-th/phy#37]
While its true that is incorrect to issue ```phy.change({name:"solid1", wake:true}) - the worker throws an unhandled exception and dies. 

I fixed it in physx.module just adding a check (A.wake && I.wakeUp && i.wakeUp())

```if (I.isBone || (A.sleep && (I.putToSleep(), g = !1), A.wake && I.wakeUp && I.wakeUp() ...````

**Comment by lo-th** [comment]
ok thanks 
is fixe 
if(!b.isBone && b.type === 'body')
