### ISSUE TITLE
Question: does this engine support convex hulls, or full mesh collisions?

### ISSUE THREAD

**Issue by salamanders** [lo-th/phy#4]
I was hoping to make a chain (out of hundreds of linked torus shaped objects), but that isn't a convex hull. Does this project support full mesh-based collisions?  It *looks* like it does with the gear demo, but that may have been some creative modelling of multiple convex shapes glued together.

Thanks!  This project looks amazing!

**Comment by lo-th** [comment]
i think last version of ammo can do that 
but i'm on big update soon with many new :)
i think the best for torus is use compound with sphere ( much faster )

**Comment by salamanders** [comment]
I'm very curious to learn more about "compound with sphere", I don't quite know what you mean.
I'd like to link together about 5,000 of this and see how it folds up, without it breaking or un-linking.

![torus](https://user-images.githubusercontent.com/85366/206034120-b9a4cd26-f63d-4009-a338-2af79851308c.png)

**Comment by lo-th** [comment]
use sphere and place in circle 
but 5000 :)
