### ISSUE TITLE
API Documentation please

### ISSUE THREAD

**Issue by prasanna-gmail** [lo-th/phy#6]
Please provide some reference to any API documentation 
Like how to play pause animation and physics
get/set the mas velocity on runtime and other available properties of bodies
enable disable physics in runtime
change materials in runtime

thanks for reading...

**Comment by lo-th** [comment]
is simple go on main 
click on EDIT and you have full code of the demo 
you can edit this code dynamically, save or load

**Comment by prasanna-gmail** [comment]
Thanks for the quick response
Hope I am new to it so not able to understand
pause I was able to do by calling **phy.pause(true)**
but not able to get mass, velocity, or able to know what are the properties available to get and set
please guide.

thanks for this repo.

**Comment by lo-th** [comment]
if you need velocity report use 
phy.set({ full:true })
now you have velocity and angular

**Comment by prasanna-gmail** [comment]
thanks
it works

**Comment by lo-th** [comment]
Documentation is on progress

**Comment by lo-th** [comment]
for the moment is just start but i will implement soon

**Comment by prasanna-gmail** [comment]
sure thanks
